### ISSUE TITLE
NameError in deploy-model-churn-prediction notebook

### ISSUE THREAD

**Issue by Scotto1989** [lfbraz/azure-data-science-e2e#5]
In the deploy-model-churn-prediction notebook, when Call the API (CMD 27) is run, an error is generated for the line "headers["Authorization"] = "Bearer {service_key}".format(service_key=dev_service_key)". The following message is displayed: "NameError: name 'headers' is not defined".

**Comment by lfbraz** [comment]
Thank you @Scotto1989. I've pushed a new change to fix this issue. Please check if it is OK now.
